[package]
name = "sbs-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sbs-api-internal = "0.1.1"
sbs-api-macro = "0.1.0"